Add files via upload
0x4261756D/CCS_scripts pull request #51
Opened 2024-06-21 15:59 UTC by NinPato

Bitte die passenden Boxen anclicken:
- [ ] Der PR beinhaltet ein oder mehrere scripts welche getestet wurden und funktionieren.
- [ ] Der PR beinhaltet ein oder mehrere Bilder welche von Aubertin abgesegnet wurden und keine Urheberrechte verletzen.
- [ ] Der PR beinhaltet eine oder mehrere Datenbanken (cdb Dateien) welche den Richtlinien aus [readme](https://github.com/0x4261756D/CCS_scripts/blob/master/README.md) genügen.

2024-06-26 14:55 UTC, 0x4261756D commented
Please move the files to their appropriate folders (pictures in pics/, scripts in scripts/Firebound)

2024-06-26 16:07 UTC, 0x4261756D requested changes
Overall the PSCT could need an overhaul, I did not comment on all cards that need one.

2024-06-26 16:07 UTC, 0x4261756D commented on 900000023.jpg
PSCT is weird

2024-07-03 17:26 UTC, NinPato commented
> Please move the files to their appropriate folders (pictures in pics/, scripts in scripts/Firebound)

Kann ich das in Github oder muss ich alles Rausschmeissen und neu hochladen?

2024-07-03 17:34 UTC, NinPato commented
Kann man das irgendwie löschen? Mir fallen mehr und mehr Fehler auf die ich noch korrigieren muss, würde dann re-submitten

2024-07-03 19:43 UTC, closed without merging

2024-07-03 19:44 UTC, Rundas01 commented
Geschlossen auf Wunsch des Autors