Iron Chain Support
0x4261756D/CCS_scripts pull request #52
Opened 2024-08-11 08:28 UTC by Coroln

-Iron Chain Minotaur
-Iron Chain Hound
-Millennium Chain
-Iron Chain Ring (Made by NIOIN)

Bitte die passenden Boxen anclicken:
- [x] Der PR beinhaltet ein oder mehrere scripts welche getestet wurden und funktionieren.
- [ ] Der PR beinhaltet ein oder mehrere Bilder welche von Aubertin abgesegnet wurden und keine Urheberrechte verletzen.
- [x] Der PR beinhaltet eine oder mehrere Datenbanken (cdb Dateien) welche den Richtlinien aus [readme](https://github.com/0x4261756D/CCS_scripts/blob/master/README.md) genügen.

2024-08-11 19:31 UTC, 0x4261756D requested changes
Seems almost ready. I had a few small questions and suggestions but once those are sorted out I'll be happy to merge this

2024-08-11 19:31 UTC, 0x4261756D commented on script/Iron Chain/c30000008.lua
> +    return re:GetHandler():GetCode()~=id and (r&REASON_EFFECT)~=0 and eg:IsExists(s.cfilter,1,nil,1-tp)
Wouldn't this limit the condition to mill by effect, so not trigger on mill for cost?

2024-08-11 19:31 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +s.listed_series={0x25}
Why does this card have this but the others don't? E.g. Millenium Chain also mentions Iron Chain

2024-08-11 19:31 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_HAND)
Please fix the indentation

2024-08-11 19:31 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +    end
same as above, please fix the indentation

2024-08-11 19:31 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +  	    ct=g:GetFirst():GetLevel()
```suggestion
  	    local ct=g:GetFirst():GetLevel()
```

2024-08-11 19:31 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +	    if #g>0 then
You already checked this above with `g:GetCount()>0`

2024-08-11 19:31 UTC, 0x4261756D commented on pics/98574213.png
small nitpick:
* If you control no monster -> If you control no monsters
* except Synchro Monster -> except Synchro Monsters
* of your opponents Deck -> of your opponent's Deck

2024-08-11 19:31 UTC, 0x4261756D commented on script/Iron Chain/c98574213.lua
same as above, please fix the indentation

2024-08-11 19:34 UTC, 0x4261756D commented
Oh, another thing I almost forgot (and about which we should most likely be better in this repo in general): Could you include credits for the images if needed? There is a Credits.txt file in the pics folder for that

2024-08-11 20:04 UTC, Coroln commented on script/Iron Chain/c30000008.lua
> +    local rc=re:GetHandler()
when i delete it the script bricks i already testet it

2024-08-11 20:05 UTC, Coroln commented on script/Iron Chain/c30000008.lua
> +    return re:GetHandler():GetCode()~=id and (r&REASON_EFFECT)~=0 and eg:IsExists(s.cfilter,1,nil,1-tp)
i dont know NIOIN made this card, but it works like intendet with the Iron Chain monster

2024-08-11 20:07 UTC, Coroln commented on script/Iron Chain/c67786887.lua
> +s.listed_series={0x25}
weil ich es vergessen habe, aber es ist auch nicht nötig weil es bisher keine karte gibt die dannach sucht, also kann mann es einfach erstmal ignorieren

2024-08-11 20:15 UTC, 0x4261756D commented on script/Iron Chain/c30000008.lua
> +    return re:GetHandler():GetCode()~=id and (r&REASON_EFFECT)~=0 and eg:IsExists(s.cfilter,1,nil,1-tp)
yes, because they mill for effect. The text says "Each time cards are sent from your opponent's deck to the GY" so it should include mill for cost. the `and (r&REASON_EFFECT)~=0` limits it to only trigger if the milling happens as an effect.

2024-08-11 20:35 UTC, Coroln commented on script/Iron Chain/c67786887.lua
> +  	    ct=g:GetFirst():GetLevel()
does it make a difference?

2024-08-11 20:36 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +  	    ct=g:GetFirst():GetLevel()
In general it does but it might not be relevant here.

2024-08-11 20:40 UTC, Coroln commented on script/Iron Chain/c67786887.lua
> +	    if #g>0 then
what exactly do you mean?

2024-08-11 20:41 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +	    if #g>0 then
`g:GetCount()` is equivalent to `#g`

2024-08-11 20:43 UTC, Coroln commented on script/Iron Chain/c67786887.lua
> +	    if #g>0 then
oh thats what you mean and how should i change that because i took that from existing scripts thats why i didn't question it

2024-08-11 20:56 UTC, 0x4261756D commented on script/Iron Chain/c67786887.lua
> +	    if #g>0 then
you can just delete the `if #g>0 then` line and the corresponding `end`

2024-08-12 00:50 UTC, 0x4261756D commented on pics/30000008.png
That image is a jpg, not a png. Please rename

2024-08-12 01:30 UTC, 0x4261756D approved these changes
Thank you for your time and patience implementing my suggestions. I'll go ahead and merge this now .)

2024-08-12 01:31 UTC, merged